// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: FileTransfer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileTransferClient is the client API for FileTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileTransferClient interface {
	// Sends a greeting
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileTransfer_UploadFileClient, error)
}

type fileTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewFileTransferClient(cc grpc.ClientConnInterface) FileTransferClient {
	return &fileTransferClient{cc}
}

func (c *fileTransferClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileTransfer_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileTransfer_ServiceDesc.Streams[0], "/fileTransfer.FileTransfer/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransferUploadFileClient{stream}
	return x, nil
}

type FileTransfer_UploadFileClient interface {
	Send(*UploadFileStruct) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type fileTransferUploadFileClient struct {
	grpc.ClientStream
}

func (x *fileTransferUploadFileClient) Send(m *UploadFileStruct) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTransferUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTransferServer is the server API for FileTransfer service.
// All implementations must embed UnimplementedFileTransferServer
// for forward compatibility
type FileTransferServer interface {
	// Sends a greeting
	UploadFile(FileTransfer_UploadFileServer) error
	mustEmbedUnimplementedFileTransferServer()
}

// UnimplementedFileTransferServer must be embedded to have forward compatible implementations.
type UnimplementedFileTransferServer struct {
}

func (UnimplementedFileTransferServer) UploadFile(FileTransfer_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileTransferServer) mustEmbedUnimplementedFileTransferServer() {}

// UnsafeFileTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileTransferServer will
// result in compilation errors.
type UnsafeFileTransferServer interface {
	mustEmbedUnimplementedFileTransferServer()
}

func RegisterFileTransferServer(s grpc.ServiceRegistrar, srv FileTransferServer) {
	s.RegisterService(&FileTransfer_ServiceDesc, srv)
}

func _FileTransfer_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServer).UploadFile(&fileTransferUploadFileServer{stream})
}

type FileTransfer_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadFileStruct, error)
	grpc.ServerStream
}

type fileTransferUploadFileServer struct {
	grpc.ServerStream
}

func (x *fileTransferUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTransferUploadFileServer) Recv() (*UploadFileStruct, error) {
	m := new(UploadFileStruct)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTransfer_ServiceDesc is the grpc.ServiceDesc for FileTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileTransfer.FileTransfer",
	HandlerType: (*FileTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FileTransfer_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "FileTransfer.proto",
}
